.PHONY: kvprot_llt kvprot_llt_cov run_kvprot_llt run_kvprot_llt_cov clean_kvprot_llt kvprot_llt_clean

kvprot_llt:
	$(MAKE) -C testcase kvprot_llt

kvprot_llt_cov:
	$(MAKE) -C testcase kvprot_llt_cov

run_kvprot_llt:
	$(MAKE) -C testcase run_kvprot_llt

run_kvprot_llt_cov:
	$(MAKE) -C testcase run_kvprot_llt_cov

clean_kvprot_llt:
	$(MAKE) -C testcase clean_kvprot_llt

kvprot_llt_clean:
	$(MAKE) -C testcase kvprot_llt_clean
